apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-extension
  namespace: argocd      
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/argoproj-labs/rollout-extension
    targetRevision: HEAD
    path: manifests
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).   
    syncOptions:
      - CreateNamespace=true
